server {
    listen 80;

    location /gallery/ {
        proxy_pass http://gallery/;
    }

    location /login/ {
        proxy_pass http://login/;
    }

    location /portfolio/ {
        proxy_pass http://portfolio/;
    }
}
