apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  labels:
    app: my-app
spec:
  selector:
    app: my-app
  ports:
  - port: 8080
    targetPort: 80
    name: http
  - port: 9113
    targetPort: 9113
    name: metrics
